
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres

  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    topics:
      transfer-notifications: transfer.notifications

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

resilience4j:
  retry:
    instances:
      fraudRetry:
        max-attempts: 3
        wait-duration: 200ms
  circuitbreaker:
    instances:
      fraudCircuit:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 1s
  bulkhead:
    instances:
      fraudBulkhead:
        max-concurrent-calls: 20
        max-wait-duration: 0

